In [2]:
import pickle as pkl
import pandas as pd
import os 
import numpy as np
import io
os.getcwd()
#fp = open("dicom_ etadata_df.pkl")
#fp
with open("dicom_metadata_df.pkl", "rb") as f:
    object = pkl.load(f)
    
df = pd.DataFrame(object)
df.to_csv(r'dicom_metadata_df.csv')

## Subsetting DF by Our Variables of Interest-- Only keeping first 100 as Trial Data

In [13]:
df['(0012, 0030) Clinical Trial Site ID']
filter_var_1="(0008, 0070) Manufacturer"
filter_var_2="(0008, 1090) Manufacturer's Model Name"
filter_var_3="(0018, 1000) Device Serial Number"
filter_var_4="(0012, 0030) Clinical Trial Site ID"

csv_file_name="metadata_100subset_df.csv"

#text_file_gen(df,filter_var)
df[[filter_var_1,filter_var_2,filter_var_3,filter_var_4]].head(100).to_csv(csv_file_name)

In [15]:
metadata_subset_df=pd.read_csv(csv_file_name)
metadata_subset_df.head()
metadata_subset_df["Unnamed: 0"]

0      700804
1     4168501
2     2127103
3     3558001
4     1597503
       ...
95    1473304
96     347204
97    1552804
98    2933901
99    3064701
Name: Unnamed: 0, Length: 100, dtype: int64

# STOP HERE Below is stats and exploration of data-- not important to this project but keeping here for now for future reference

### Below Cell Generates text files of XRay ID #s for each filter_var-- wasn't used in this part of the project but keeping for future reference

In [ ]:
df.head()
filter_var='(0008, 0070) Manufacturer'

In [ ]:
#names = set(df.loc[:,"LOC"])
def text_file_gen(df,filter_var):
    names=df[filter_var].unique()
    print(names)
    for name in names:
        variable = df[df[filter_var]==name]
        variable=list(variable.index)
        with io.open(str(name) + ".txt", 'w') as f:
            for item in variable:
                f.write("%s\n" % item)
            print("Done with " + str(name))
        print(len(variable))
#text_file_gen(df,filter_var)

In [ ]:
names=df[filter_var].unique()
print(names)
with open(r'Manufacturer_Names.txt', 'w') as fp:
    for item in names:
        # write each item on a new line
        fp.write("%s\n" % item)
    print('Done')
df[filter_var].to_csv(r'Manufacturer.csv')

In [16]:
#metadata_subset_df=metadata_subset_df.head()
#metadata_subset_df.to_csv(r'metadata_supersubset_df.csv',index=False)

# Uncomment to convert proc_stats and seq_metadata pkls to csvs

In [18]:
with open("dicom_proc_stats_df.pkl", "rb") as f:
    object = pkl.load(f)
    
df = pd.DataFrame(object)
df.to_csv(r'dicom_proc_stats_df.csv')

In [17]:
with open("dicom_seq_metadata_df.pkl", "rb") as f:
    object = pkl.load(f)
    
df = pd.DataFrame(object)
df.to_csv(r'dicom_seq_metadata_df.csv')

In [5]:
dicom_proc_stats_df = pd.read_csv('dicom_proc_stats_df.csv')
dicom_proc_stats_df.head()

,Unnamed: 0,Raw Height,Raw Width,Raw Min,Raw Max,Raw mean,Raw variance,Raw skewness,Raw kurtosis,Rescale Min,...,Mono1 Win mean,Mono1 Win variance,Mono1 Win skewness,Mono1 Win kurtosis,Mono1 VOI Min,Mono1 VOI Max,Mono1 VOI mean,Mono1 VOI variance,Mono1 VOI skewness,Mono1 VOI kurtosis
0,700804,2048,2494,0,3065,21848.717816,2.142204e+08,-0.030175,-1.531385,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4168501,2021,2021,0,16383,11269.727083,5.595539e+07,0.613114,6.377851,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2127103,1760,2140,0,608,9819.818156,2.193003e+08,1.719653,2.250220,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3558001,3001,3001,0,3833,28428.168652,5.124549e+08,-0.064549,-1.557716,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1597503,3485,4247,0,3599,26713.697540,4.755870e+08,0.099394,-1.585137,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
dicom_seq_metadata_df = pd.read_csv('dicom_seq_metadata_df.csv')
dicom_seq_metadata_df.head()

,BARCODE,Seq Name,Seq #,Tag,VR,Value
0,4168501,"(0008, 1110) Referenced Study Sequence",0,"(0008, 1150) Referenced SOP Class UID",UI,1.2.840.10008.3.1.2.3.1
1,4168501,"(0008, 1110) Referenced Study Sequence",0,"(0008, 1155) Referenced SOP Instance UID",UI,1.2.840.113745.101000.1035000.41476.5146.18218866
2,4168501,"(0008, 1120) Referenced Patient Sequence",0,"(0008, 1150) Referenced SOP Class UID",UI,1.2.840.10008.3.1.2.1.1
3,4168501,"(0008, 1120) Referenced Patient Sequence",0,"(0008, 1155) Referenced SOP Instance UID",UI,1.2.840.113745.101000.1035000.38480.7338.5733294
4,4168501,"(0008, 2112) Source Image Sequence",0,"(0008, 1150) Referenced SOP Class UID",UI,1.2.840.10008.5.1.4.1.1.1.1.1

In [7]:
dicom_metadata_df = pd.read_csv('dicom_metadata_df.csv')
dicom_metadata_df.head()

/var/folders/gd/78f_7bqs5f13r2fw96ld0wyh0000gn/T/ipykernel_24325/3163063219.py:1: DtypeWarning: Columns (28,70,115,116,134,217,218,219,220,224,225) have mixed types. Specify dtype option on import or set low_memory=False.
  dicom_metadata_df = pd.read_csv('dicom_metadata_df.csv')

,Unnamed: 0,"(0008, 0005) Specific Character Set","(0008, 0008) Image Type","(0008, 0012) Instance Creation Date","(0008, 0013) Instance Creation Time","(0008, 0016) SOP Class UID","(0008, 0018) SOP Instance UID","(0008, 0020) Study Date","(0008, 0022) Acquisition Date","(0008, 0030) Study Time",...,"(0020, 0052) Frame of Reference UID","(0040, 0250) Performed Procedure Step End Date","(0040, 0251) Performed Procedure Step End Time","(0018, 1170) Generator Power","(0018, 5020) Processing Function","(0018, 5021) Postprocessing Function","(0054, 0410) Patient Orientation Code Sequence","(0054, 0414) Patient Gantry Relationship Code Sequence","(0028, 0106) Smallest Image Pixel Value","(0028, 0107) Largest Image Pixel Value"
0,700804,ISO_IR 100,"['DERIVED', 'PRIMARY']",20050513.0,91344.0,1.2.840.10008.5.1.4.1.1.1,1.3.6.1.4.1.21767.172.16.8.165.1158825987.343....,20050513,20050513.0,92624.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4168501,ISO_IR 100,"['ORIGINAL', 'PRIMARY']",NaN,NaN,1.2.840.10008.5.1.4.1.1.1.1,1.3.6.1.4.1.21767.127.0.0.1.1377304274.0.0.1.1,20130806,20130806.0,142822.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2127103,NaN,"['DERIVED', 'PRIMARY', 'POST_PROCESSED', '', '...",NaN,NaN,1.2.840.10008.5.1.4.1.1.1,1.3.6.1.4.1.21767.172.16.8.165.1183056852.849....,20070611,20070611.0,112952.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3558001,ISO_IR 100,NaN,NaN,NaN,1.2.840.10008.5.1.4.1.1.1,1.3.6.1.4.1.21767.127.0.0.1.1284501153.0.0.1.1,20100714,20100714.0,132755.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1597503,NaN,"['ORIGINAL', 'SECONDARY', 'RADIOGRAPH']",20060726.0,191749.0,1.2.840.10008.5.1.4.1.1.1,1.3.6.1.4.1.21767.172.16.8.182.1153941474.911....,20060707,20060707.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN